### PR TITLE
[VGNWB-345] Add pagination for repo collections

### PR DESCRIPTION
**Pull request by nowke**
Corresponding PRs:
* Vogon Backend - https://github.com/diging/vogon-web/pull/189
* Amphora - https://github.com/diging/amphora/pull/155

### CODE REVIEW

**Comment by tjquinn1** [comment]
I could not login in. I get a 404. 
Screen Shot 2020-08-04 at 2 47 46 PM

Screen Shot 2020-08-04 at 2 50 51 PM

 It appears it is trying to make a request to itself for the token. Not sure why this changed.

**Comment by nowke** [comment]
I am not getting this error. I am able to login with the same branch, FE and BE.

The value is taken from `VUE_APP_BASE_URL=http://localhost:8000/api/v2/` in `.env` file of Frontend. Could you check that?

**Comment by tjquinn1** [comment]
We are going to leave this ticket unmerged until we deploy the corresponding amphora version

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Pull request merged**
