### PR TITLE
[VGNWB-329] Project collaboration

### PR DESCRIPTION
**Pull request by nowke**
Related BE - diging/vogon-web#188

Created new PR as branch was force pushed to resolve conflicts.

### CODE REVIEW

**Comment by tjquinn1** [comment]
resolve conflicts

**Comment by tjquinn1** [comment]
I am able to add a collaborator but when I add annotate something and then open the text as the other user I can not see their annotations. Both users annotations should be available to both users. Projects that are shared with me should be indicated in the projects list, maybe a tag or something like that.

**Comment by nowke** [comment]
> I am able to add a collaborator but when I add annotate something and then open the text as the other user I can not see their annotations. Both users annotations should be available to both users. Projects that are shared with me should be indicated in the projects list, maybe a tag or something like that.

This should be resolved now.

**Comment by tjquinn1** [comment]
fix BE build issues

**Comment by tjquinn1** [comment]
fix BE build issues

**Pull request closed without merging**
