### PR TITLE
[VGNWB-328] Add export affiliation button

### PR DESCRIPTION
**Pull request by nowke**
Related BE - https://github.com/diging/vogon-web/pull/183

### CODE REVIEW

**Comment by tjquinn1** [comment]
Reopen when the issue on the backend are resolved

**Comment by nowke** [comment]
Resolved BE issues

**Comment by tjquinn1** [comment]
See backend pull request

**Comment by nowke** [comment]
Resolved Backend issues

**Review by tjquinn1 — CHANGES_REQUESTED** [review]
I can't login on this branch it. Throws a 404 not found. I get the following errors in the terminal. It appears that is trying to make a request to itself http://localhost:8080/annotate/token/verify/

```
ERROR in /Users/taylorquinn/Desktop/vogon/vogon-web-client/src/components/auth/SignUpForm.vue
82:7 Object is possibly 'undefined'.
    80 | 			.catch((error: AxiosError) => {
    81 | 		this.error = true;
  > 82 | 		if (error.response.status === 412) {
       | 		    ^
    83 | 			this.errorMsg = String(error.response.data[0]).slice(0, -1);
    84 | 			for (let i = 1; i < error.response.data.length; i++) {
    85 | 			this.errorMsg = this.errorMsg.concat(', ' + String(error.response.data[i]).slice(0, -1));
ERROR in /Users/taylorquinn/Desktop/vogon/vogon-web-client/src/components/auth/SignUpForm.vue
83:27 Object is possibly 'undefined'.
    81 | 		this.error = true;
    82 | 		if (error.response.status === 412) {
  > 83 | 			this.errorMsg = String(error.response.data[0]).slice(0, -1);
       | 			                       ^
    84 | 			for (let i = 1; i < error.response.data.length; i++) {
    85 | 			this.errorMsg = this.errorMsg.concat(', ' + String(error.response.data[i]).slice(0, -1));
    86 | 			}
ERROR in /Users/taylorquinn/Desktop/vogon/vogon-web-client/src/components/auth/SignUpForm.vue
84:24 Object is possibly 'undefined'.
    82 | 		if (error.response.status === 412) {
    83 | 			this.errorMsg = String(error.response.data[0]).slice(0, -1);
  > 84 | 			for (let i = 1; i < error.response.data.length; i++) {
       | 			                    ^
    85 | 			this.errorMsg = this.errorMsg.concat(', ' + String(error.response.data[i]).slice(0, -1));
    86 | 			}
    87 | 				} else {
ERROR in /Users/taylorquinn/Desktop/vogon/vogon-web-client/src/components/auth/SignUpForm.vue
85:55 Object is possibly 'undefined'.
    83 | 			this.errorMsg = String(error.response.data[0]).slice(0, -1);
    84 | 			for (let i = 1; i < error.response.data.length; i++) {
  > 85 | 			this.errorMsg = this.errorMsg.concat(', ' + String(error.response.data[i]).slice(0, -1));
       | 			                                                   ^
    86 | 			}
    87 | 				} else {
    88 | 					this.errorMsg = 'User could not be created';
```

**Comment by nowke** [comment]
Reopening as discussed.

**Comment by tjquinn1** [comment]
This throws an error when I try to export the relations. Am I missing a template?

ERROR:django.request:Internal Server Error: /api/v2/project/1/export_affiliations
Traceback (most recent call last):
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/taylorquinn/Desktop/vogon/vogon-web/annotations/views/project_views.py", line 80, in export_affiliations
    template = RelationTemplate.objects.get(name="Affiliation")
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/taylorquinn/Desktop/vogon/venv/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
annotations.models.RelationTemplate.DoesNotExist: RelationTemplate matching query does not exist.

**Comment by nowke** [comment]
Yes. I have added the template definition in the docs - https://diging.atlassian.net/wiki/spaces/VGNWB/pages/2086273044/Vogon+Initial+Setup#Affiliation-Template

**Comment by tjquinn1** [comment]
see backend

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
See backend

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Fix conflicts

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Pull request merged**
