### PR TITLE
[VGNWB-348] Refactor template creation

### PR DESCRIPTION
**Pull request by nowke**
* Refactor template creation logic - removed VueJS antipattern with respect to mutating child props
* Fix bugs with empty fields on edit template page
* Fix node label mandatory logic

Related BE - https://github.com/diging/vogon-web/pull/195

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Any hrefs need to be changed to router-links or use the to attribute. Without one of these the path does not render any prefixes should as dev. The href on the create button for the template is an example. When you click create, throws a 404 because it tries to open the wrong path

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
When I search for a concept I get no data. It doesn't throw errors in the console and it doesn't make a network call so I think its a UI issue and not a backend or setup issue. 

Lets take the brackets off the Select a concept messages in the other two boxes.

Screen Shot 2021-03-04 at 9 07 20 PM

**Comment by tjquinn1** [comment]
Make it so, Jenkins

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make is so, Jenkins.

**Comment by tjquinn1** [comment]
Screen Shot 2021-03-10 at 11 44 57 AM
After thinking about this, lets move the card below the search box and give it rounded corners. Add some help text above the search box that says search for concept or something along those lines.

**Comment by nowke** [comment]
> Screen Shot 2021-03-10 at 11 44 57 AM
> 
> After thinking about this, lets move the card below the search box and give it rounded corners. Add some help text above the search box that says search for concept or something along those lines.

Changes done

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Review by tjquinn1 — APPROVED** [review]

**Pull request merged**
