### PR TITLE
[VGNWB-323] Fix concept type label value

### PR DESCRIPTION
**Pull request by nowke**
Related Backend PR - https://github.com/diging/vogon-web/pull/192

### CODE REVIEW

**Review by yuvakurakula — APPROVED** [review]

**Comment by tjquinn1** [comment]
See backend comments

**Comment by tjquinn1** [comment]
reopen when backend is fixed

**Comment by tjquinn1** [comment]
fix build issues on BE

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
reopen with backend

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Pull request merged**
